### ISSUE TITLE
Text instead of CSV

### ISSUE THREAD

**Issue by Antti** [reevoo/anon#19]
Isn't it better idea to generally use text anon instead of CSV?
* It should be faster
* It wouldn't change the structure of CSV document (delimiters, new lines, etc).

**Comment by reneklacan** [comment]
Makes sense

**Comment by errm** [comment]
It would be harder to do #14 with this

**Comment by jonnyarnold** [comment]
The reason that CSV was added was because of the original data that we built the application to anonymise. In this data, there was an e-mail column, but some of the entries in this column weren't e-mail addresses (e.g. `firstname@lastname`, which doesn't have a TLD); we wanted to make sure everything in the column was anonymised, which forced us to CSV.

If we think this use case is too rare we can remove it.
